services:
  - type: web
    name: fittracker-api
    runtime: docker
    branch: main
    dockerContext: .
    dockerfilePath: backend/Dockerfile
    healthCheckPath: /actuator/health
    autoDeployTrigger: checksPass
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PWD
        sync: false
      - key: APP_JWT_SECRET
        generateValue: true
      - key: APP_AUTH_COOKIE_SECURE
        value: "true"
